version: "3.9"
services:

  api:
    container_name: nest_api
    build: .
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - .:/home/api

#    environment:
#      DB_HOST: database
#      DB_PORT: 3306

  database:
    container_name: nest_db
    restart: always
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
    ports:
      - "${DB_PORT}:3306"